[package]
name = "wawi"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
iced = { version = "0.12.1", features = ["image", "svg"]  } # add tokyo if needed
iced_layershell = "0.2.7"
